module.exports = {
    STATUS_CODE: {
        SUCCESS_STATUS: 200,
        CREATED_SUCCESSFULLY_STATUS: 201,
        BAD_REQUEST_ERROR_STATUS: 400,
        UNAUTHORIZED_ERROR_STATUS: 401,
        INTERNAL_SERVER_ERROR_STATUS: 500
    }
}